name: tlc
description: "An app for TLC Alterosa coordinators"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crypto: ^3.0.6
  csv: ^6.0.0
  cupertino_icons: ^1.0.2
  dotlottie_loader: ^0.0.5
  dotted_border: ^2.1.0
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.5.0
  flutter_native_splash: ^2.4.6
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  provider: ^6.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/lottie/loading.lottie
    - assets/image/tlc_logo.png
    - assets/image/wave.png
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icon/Guadalupe.ttf
